receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

extensions:
  sigv4auth:
    region: "ap-northeast-1"
    service: "aps"

exporters:
  otlp/tempo:
    endpoint: "localhost:5317"
    tls:
      insecure: true
    sending_queue:
      enabled: true
  prometheusremotewrite:
    endpoint: "https://XXXXXXXXXXXXXX/api/v1/remote_write"
    auth:
      authenticator: sigv4auth
  debug:
    verbosity: detailed
  otlphttp/loki:
    endpoint: "http://localhost:3100/otlp"

processors:
  batch:

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [1ms, 10ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 700ms, 800ms, 900ms, 1s]
    metrics_flush_interval: 3s
    metrics_expiration: 10s
    exemplars:
      enabled: true

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [debug, prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/tempo, spanmetrics]
    logs:
      receivers: [otlp] 
      processors: []
      exporters: [otlphttp/loki]
